### ISSUE TITLE
Copyright section is outdated

### ISSUE THREAD

**Issue by maurezen** [jcabi/jcabi-latex-maven-plugin#10]
Copyright sections still feature 2014 as a year.

**Comment by dmarkov** [comment]
this task will get someone's attention soon

**Comment by dmarkov** [comment]
@dpisarenko please proceed, it's yours

**Comment by dpisarenko** [comment]
@dmarkov Please find someone to review PR https://github.com/jcabi/jcabi-latex-maven-plugin/pull/11 .

**Comment by dpisarenko** [comment]
@maurezen Please look at the updated code and if everything is OK, close the task. Thanks!

**Comment by dmarkov** [comment]
@maurezen thanks a lot for reporting, **15 mins** added to your acc, pmt ID `50302967`

**Comment by dpisarenko** [comment]
@maurezen  Please look at the updated code and if everything is OK, close the task. Thanks!

**Comment by dmarkov** [comment]
@dpisarenko Much obliged! I've added **30 mins** to your account in payment "50518916". +30 added to your rating, at the moment it is: [+295](http://www.netbout.com/b/35089?open=rating)
