### ISSUE TITLE
Estimate project size

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-latex-maven-plugin#14]
There is no estimate in the project yet. We have to create one as explained [here](https://github.com/teamed/est)

**Comment by dmarkov** [comment]
@super132 the task is yours

**Comment by super132** [comment]
@dmarkov PR #17 fixed this issue. Would you please close it? Thanks.

**Comment by super132** [comment]
@dmarkov would you please close this ticket?Thanks.

**Comment by yegor256** [comment]
@rultor deploy

**Comment by super132** [comment]
@dmarkov , it has been 5 days since PR is merged. Would you please close it ?

**Comment by super132** [comment]
@dmarkov The PR has been merged for a week and this ticket is still not closed. Would you please close it?

**Comment by dmarkov** [comment]
@super132 Many thanks! **30 mins** were added to your account in Transaction ID `AP-9PP000367L206663W` (task took 166 hours and 25 mins)

+30 added to your rating, at the moment it is: [+331](http://www.netbout.com/b/35282?open=rating)

**Comment by dmarkov** [comment]
@yegor256 I'm closing the issue...
