### ISSUE TITLE
Confusing README.md

### ISSUE THREAD

**Issue by darkled** [jcabi/jcabi-latex-maven-plugin#8]
`README.md` has not clear information about the purpose of the plugin, but should have similar to http://latex.jcabi.com/index.html.

**Comment by darkled** [comment]
@yegor256 is it better now?

**Comment by yegor256** [comment]
@darkled yes, looks good now

**Comment by dmarkov** [comment]
@aoxa this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here

Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by dmarkov** [comment]
@darkled thanks for this report, I added 15 mins to your account, in transaction `50257722`

**Comment by dmarkov** [comment]
@aoxa you're holding this ticket for 15 days already. If it's not finished (and closed) in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle ([this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck)

-30 added to your rating, current score is: -120

**Comment by dmarkov** [comment]
@aoxa you've been working with this task for too long. I'm sorry, but I'll assign someone else. Please stop working with it. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle; -60 added to your rating, at the moment it is: -390

**Comment by dmarkov** [comment]
@suseika this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here. Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by Suseika** [comment]
@dmarkov The PR is merged, please close the issue.

**Comment by Suseika** [comment]
@dmarkov Who should I ask to close an issue next time: the person who created the issue, or the person who assigned me to that issue?

**Comment by Suseika** [comment]
@dmarkov It's been 2 days since this task has been closed, and the task is still on my agenda in netbout. Are you going to mark it as done?

**Comment by dmarkov** [comment]
@suseika Thank you, I have added **30 mins** to your account in payment/transaction "`AP-67D14404SV104702S`", time consumed: 144 hours and 19 mins; +30 added to your rating, current score is: [+60](http://www.netbout.com/b/35381?open=rating)
