### ISSUE TITLE
Error in Windows build: "Failed to find executable of 'gs'"

### ISSUE THREAD

**Issue by carlosmiranda** [jcabi/jcabi-latex-maven-plugin#9]
I was trying to see whether the patch applied in #3 successfully fixed the error described in #1. Sure enough, the original error `Cannot run program "/usr/bin/which"` has been fixed. However, I am getting a different error now.

```
[INFO] ------------------------------------------------------------------------
[INFO] Building s3auth 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ s3auth ---
[INFO] Deleting C:\Users\Carlos Miranda\git\s3auth\target
[INFO]
[INFO] --- jcabi-latex-maven-plugin:1.1:compile (default) @ s3auth ---
[INFO] directories created for C:\Users\Carlos Miranda\git\s3auth\target\site\latex
[INFO] directory created: C:\Users\Carlos Miranda\git\s3auth\target\latex-temp
[INFO] directory C:\Users\Carlos Miranda\git\s3auth\target\latex-temp\packages created
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] s3auth ............................................ FAILURE [0.860s]
[INFO] s3auth-hosts ...................................... SKIPPED
[INFO] s3auth-relay ...................................... SKIPPED
[INFO] s3auth-rest ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.782s
[INFO] Finished at: Wed Jan 07 10:58:53 CET 2015
[INFO] Final Memory: 10M/111M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.jcabi:jcabi-latex-maven-plugin:1.1:compile (default) on project s3auth: Failed to com
pile 'packages.tex': Failed to find executable of 'gs' -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

We should fix this error so that it would build on Windows. Note that in this case, I was trying to build the site of [S3Auth](https://github.com/yegor256/s3auth) project with version 1.1 of `jcabi-latex-maven-plugin`. The command that was used is `mvn clean site`.

**Comment by dmarkov** [comment]
I'm aware of the task, give me some time to find a developer...

**Comment by dmarkov** [comment]
@nhekfqn this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here; The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by dmarkov** [comment]
@carlosmiranda many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `49977426`

**Comment by nhekfqn** [comment]
@dmarkov how exactly should it be fixed? if user has no gs command on his/her machine, s/he will see this error. jcaby-latex plugin documentations states user has to have Netpbm installed but there are a few options for Windows users: http://netpbm.sourceforge.net/getting_netpbm.php If cygwin option is used, it should work (as it works on linux), other options need to be checked. Please clarify what is supposed setup for Windows users to use this plugin. If noone ever actually tried to use it on windows - we need separate task to investigate.

**Comment by yegor256** [comment]
@nhekfqn in this ticket we don't care about users, but only about developers. The build fails on Windows and this is the problem @carlosmiranda is reporting. We need to find a way to skip this test on Windows, I guess. That's all. @carlosmiranda am I right?

**Comment by nhekfqn** [comment]
@yegor256 as the issue states "mvn clean site" command fails for project s3auth when version 1.1 of jcabi-latex-maven-plugin is used. I see that default phase for jcabi-latex-maven-plugin execution is pre-site, so I assume plugin is intended for use with site maven goal and disabling it won't be a proper fix. The reason plugin execution fails on windows is that it is implemented to run only on *nix, as I can see. So it is not quite a bug, it is a task to add windows support for the plugin. Am I missing something?

**Comment by yegor256** [comment]
@nhekfqn you're right, I'm wrong. I think the best we can do is to inform Windows users that they have to install Ghostscript and make `gs` command available on `PATH`. If such a command is not executable, we should just fail with a proper message. Make sense?

**Comment by nhekfqn** [comment]
@yegor256 it should work with latex, dvips, gs and 4 pbm commands available on path, assuming it works on *nix, I didn't check it though. If you are sure it will work, then we only need to update documentation, if not, I think it worth checking.

**Comment by yegor256** [comment]
At the moment it won't work on Windows, even if `gs` is installed. Because of this: `Cannot run program "/usr/bin/which"`. At the moment the plugin doesn't understand Windows at all, that's the problem

**Comment by nhekfqn** [comment]
@yegor256  as @carlosmiranda mentioned "which" was fixed here: https://github.com/darkled/jcabi-latex-maven-plugin/commit/3f9bbcfb78892a0ef6a1bbc0395952f198720a76 that code is in current master of plugin. What do we do with this issue? I can install all dependencies, check if it will work on windows with all executables available on path and then add statement about dependencies to documentation (not sure how, at least I can provide text for documentation) or report another issue, if plugin will not work even with all dependencies. Does it sound good enough for 30 min task?

**Comment by nhekfqn** [comment]
@dmarkov it looks like I should reject this ticket (see discussion above). How do I do that? It this message enough?

**Comment by yegor256** [comment]
@dmarkov please assign someone else to this task

**Comment by dmarkov** [comment]
> @dmarkov please assign someone else to this task

@yegor256 right, I will find someone else, no problem

**Comment by dmarkov** [comment]
@marczeeee could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here... The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by Marczeeee** [comment]
@carlosmiranda @yegor256 I checked the plugin and if one installs all the necessary commands on Windows the plugin will be able to locate them. But there is another problem: the processing part of the plugin is also written to work with only *nix, and it also has to be refactored to be able to produce and run Windows complying transformation command chains. My question is that in this case what should be the scope of this issue?

**Comment by yegor256** [comment]
@Marczeeee I think we should just fail if it's Windows. The plugin should just report that "sorry, I don't run on Windows". besides that, we should document that in `README` and in `index.apt.vm`

**Comment by Marczeeee** [comment]
@carlosmiranda Related pull request #12 was merged. Please close this issue.

**Comment by carlosmiranda** [comment]
@Marczeeee Indeed, thank you.

**Comment by dmarkov** [comment]
@marczeeee Thank you, I've added **30 mins** to your account in payment/transaction "`50597579`"; added +30 to your rating, now it is equal to +120
